### ISSUE TITLE
Superuser - clients - login

### ISSUE THREAD

**Issue by Ciberconsultant** [nirajconverthink/CIBERCONSULTORES#10]
Once logged in to a clients interface from the superuser list of clients, upon 'logout' could we return to the superuser interface? the idea of being able to login to the clients interface as superuser is to resolve issues of support, so after dealing with it, there should be an easy way to return to the superuser interface, if that is not to complicated

**Comment by nirajconverthink** [comment]
Okay we will do this

**Comment by nirajconverthink** [comment]
Done

**Comment by nirajconverthink** [comment]
Done please check
